#!/bin/bash
set -x
SOURCE_DIR=/var/lib/tsuru
${SOURCE_DIR}/base/deploy $@

source ${SOURCE_DIR}/config

cd $CURRENT_DIR
# $2 == git-ref-id
git archive --format=tar $2 |sudo /bin/sh -c "rm -rf /app && mkdir /app && tar xvf - -C /app"
sudo /build/builder
